# Workshop 1 (Machine Learning)

## Análisis Exploratorio de Datos (EDA) con NumPy y Pandas

### Objetivo

Aplicar el ciclo completo de exploración de datos: reconocimiento inicial, limpieza (cleaning), análisis descriptivo y visualización, usando un dataset real de Kaggle.

## Fase 1 (Reconocimiento Inicial del Dataset)

### 1.1 ¿De qué trata el Dataset?

El dataset contiene las calificaciones de un conjunto de estudiantes, dataset donde se evaluan otros aspectos también, como lo puede ser el nivel de educación de los padres como también su raza o etnia, entre otros datos que pueden ser relevantes e influyentes en el desempeño de los estudiantes.

### 1.2 Primeras y Últimas filas del Dataset

Utilizaremos los métodos propios de la libreria Pandas .head() y .tail() para mostrar las primeras y las últimas cinco filas del dataset.

#### Importación de Librerias:

In [6]:
import numpy as np
import pandas as pd

#### Lectura del Dataset:

In [8]:
students_data = pd.read_csv("data/StudentsPerformance.csv")

#### Primeras 5 filas:

In [9]:
students_data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

#### Últimas 5 filas:

In [10]:
students_data.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

#### Filas y Columnas del Dataset:

In [12]:
students_data.shape

(1000, 8)